name: NuviCore Auto-Bot
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run Scraper
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python main_scraper.py

      - name: Commit and Push changes
        run: |
          git config --local user.name "NuviCore-Bot"
          git config --local user.email "bot@nuvicore.com"
          git add campionati/*.csv
          git commit -m "Update cuotas $(date)" || echo "No hay cambios"
          git push
