name: Escaneo Automatico NuviCore

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalacion
        run: pip install pandas requests beautifulsoup4 lxml
        
      - name: Ejecutar Bot
        run: python main_scraper.py
        
      - name: Guardar en GitHub
        run: |
          git config --global user.name "NuviCore-Bot"
          git config --global user.email "bot@nuvicore.com"
          mkdir -p campionati
          git add campionati/*.csv || echo "No hay archivos nuevos"
          git commit -m "Update cuotas $(date)" || echo "Nada que actualizar"
          git push origin main
